project:
  type: website
  output-dir: docs

website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: NEPS 2023 (B Prins)
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

